language: rust
sudo: false
dist: bionic

cache:
  cargo: true
  directories:
    - .cache

rust:
  - nightly
  - beta
  - stable

script:
  - |
      CARGO_OPTS=()
      if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then
        CARGO_OPTS+=("--features" "unstable")
      fi
      cargo build "${CARGO_OPTS[@]}" --workspace --release &&
      cargo run  "${CARGO_OPTS[@]}" --release --bin euler &&
      cargo test "${CARGO_OPTS[@]}" --workspace &&
      cargo bench "${CARGO_OPTS[@]}" --workspace
