[package]
name = "prime"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"
edition = "2018"

[dependencies]
num-integer = "0.1.44"
num-traits = "0.2.14"

[features]
default = []
unstable = []
